### ISSUE TITLE
Contact us form - Email Id, Mobile  and Name validation 

### ISSUE THREAD

**Issue by 2016DigiTech** [hlxsites/tlcgrp#149]
Hi Team, 
Contact us form email id, mobile and name validation.

![image](https://user-images.githubusercontent.com/112628085/232009289-ed0be480-7a56-4f6a-ba06-0b070046b4e1.png)

**Comment by vdua** [comment]
I wanted to understand the use case in detail. There can be two implementations

1. Prevent entering invalid values
2. Allow entering wrong values, but show error either on click of submit/focus out or as users type

2 is easy to solve with ootb browser validations. For 1, the problem is difficult to solve since one has to handle multiple cases, keypress, clipboard events (paste), virtual keyboards.
