### ISSUE TITLE
How  to create Salutation dropdown and First Name and Last Name input field  

### ISSUE THREAD

**Issue by 2016DigiTech** [hlxsites/tlcgrp#168]
Hi Team.

How  to create Salutation dropdown and First Name and Last Name input field for the contact form. 
We are connecting this form to SFDC hence we need this field for bring able to correctly address the names on the acknowledgement mailer. 

Please Suggest. 

@vdua @asthabh23 @rofe

**Comment by vdua** [comment]
You can create the field in spreadsheet and it will be displayed. Can you share the form where you want this so that I can have a look ?

**Comment by vdua** [comment]
If it is the contact-us form, then I have created a version of it in [drafts](https://select--tlcgrp--hlxsites.hlx.page/drafts/vdua/contact-us). It would require PR #171 to be merged for it to work

It can be styled according to your needs. Since I was not sure I just copied the current styles locally. See the below screenshot

<img width="898" alt="image" src="https://github.com/hlxsites/tlcgrp/assets/2097597/fef59162-dd2a-473c-adca-29ce91cbc5d6">
